home/urls.py
from django.conf.urls import url
from . import views

app_name = 'home'

urlpatterns = [
    url(r'^$', views.welcome, name='welcome'),
]

one/api/urls.py
from django.conf.urls import url

from .views import (
    ProfileListAPIView,
    )

urlpatterns = [
    url(r'^$', ProfileListAPIView.as_view(), name='profile-list'),
]

one/urls.py
from django.conf.urls import url
from . import views

app_name = 'one'

urlpatterns = [
    url(r'^search/$', views.search, name='search'),
]

teste/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import (
    include,
    url
    )
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    # home urls
    url(r'^', include('home.urls')),
    # one urls
    url(r'^one/', include('one.urls')),
    url(r'^api/one/', include('one.api.urls')),
    # two urls
    url(r'^two/', include('two.urls')),
    url(r'^api/two/', include('two.api.urls')),
    # three urls
    url(r'^three/', include('three.urls')),

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

three/urls.py
from django.conf.urls import url
from . import views

app_name = 'three'

urlpatterns = [
    url(r'^translate/$', views.translate, name='translate'),
]

two/api/urls.py
from django.conf.urls import url

from .views import (
    ProfileCreateAPIView,
    )

urlpatterns = [
    url(r'^create/$', ProfileCreateAPIView.as_view(), name='profile-create'),
]

two/urls.py
from django.conf.urls import url
from . import views

app_name = 'two'

urlpatterns = [
    url(r'^submit/$', views.submit, name='submit'),
]

home/models.py
from django.db import models

# Create your models here.

one/models.py
from django.db import models

class Profile(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(max_length=254, null=True, blank=True)

    def __str__(self):
        return '%s. %s' % (self.id, self.name)

three/models.py
from django.db import models

# Create your models here.

two/models.py
from django.db import models
from datetime import (
    datetime,
    timedelta,
    )

FORM_SUBMISSION_TOLERANCE = 120

class FormSubmissionManager(models.Manager):
    def check_hash(self, hash):
        submission_tolerance = datetime.now() - timedelta(seconds=FORM_SUBMISSION_TOLERANCE)
        qs = super(FormSubmissionManager, self).filter(registered__lt=submission_tolerance).delete()
        obj, created = super(FormSubmissionManager, self).get_or_create(hash=hash)
        return created

class FormSubmission(models.Model):
    hash = models.CharField(max_length=32)
    registered = models.DateTimeField(auto_now_add=True)

    objects = FormSubmissionManager()

    def __str__(self):
        return '%s. %s' % (self.id, self.registered)

home/views.py
from django.shortcuts import render

# Welcome page
def welcome(request):
    return render(request, 'home/welcome.html')

one/api/views.py
from rest_framework.filters import SearchFilter
from rest_framework.generics import (
    ListAPIView,
    )
from rest_framework.permissions import AllowAny
from ..models import Profile
from .pagination import DefaultNumberPagination
from .serializers import ProfileSerializer

class ProfileListAPIView(ListAPIView):
    serializer_class = ProfileSerializer
    filter_backends= [SearchFilter]
    search_fields = ['name', 'email']
    pagination_class = DefaultNumberPagination
    permission_classes = [AllowAny]

    def get_queryset(self, *args, **kwargs):
        queryset_list = Profile.objects.all().order_by('-id')
        return queryset_list

one/views.py
from django.shortcuts import render

# Search page
def search(request):
    return render(request, 'one/search.html')

three/views.py
from django.shortcuts import render

# locale vs Internationalization page
def translate(request):
    return render(request, 'three/translate.html')

two/api/views.py
from rest_framework.generics import CreateAPIView
from rest_framework.permissions import AllowAny
from one.models import Profile
from .serializers import ProfileCreateSerializer

class ProfileCreateAPIView(CreateAPIView):
    queryset = Profile.objects.all()
    serializer_class = ProfileCreateSerializer
    permission_classes = [AllowAny]

two/views.py
from django.shortcuts import render

# submit page
def submit(request):
    return render(request, 'two/submit.html')

home/templates/home/base.html
{% load static %}
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>B2Blue test</title>
  <meta name="description" content="B2Blue test">
  <meta name="author" content="Rodrigo Reis">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

  <!-- load boostrap css -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
  <!-- load base css -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css"/>


</head>

<body>
  <!-- load page content -->
  {% block body %}
  {% endblock %}

  <!-- loading container -->
  <div id="loading">
    <div class="spinner2"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
    <div class="spinner1"></div>
  </div>
  <!-- load jquery -->
  <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
  <!-- load i18n -->
  <script src="{% static 'libs/i18n/src/jquery.i18n.js' %}"></script>
  <script src="{% static 'libs/i18n/src/jquery.i18n.messagestore.js' %}"></script>
  <script src="{% static 'libs/i18n/src/jquery.i18n.fallbacks.js' %}"></script>
  <script src="{% static 'libs/i18n/src/jquery.i18n.parser.js' %}"></script>
  <script src="{% static 'libs/i18n/src/jquery.i18n.emitter.js' %}"></script>
  <script src="{% static 'libs/i18n/src/jquery.i18n.language.js' %}"></script>
  <script src="{% static 'libs/i18n/i18n.js' %}"></script>
  <!-- <script src="{% static 'libs/i18n/messages.json' %}"></script> -->
  <!-- load bootstrap js -->
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
  <!-- load main js -->
  <script src="{% static 'js/main.js' %}" type="text/javascript"></script>
  <!-- load one js -->
  <script src="{% static 'js/page-one.js' %}" type="text/javascript"></script>
  <!-- load two js -->
  <script src="{% static 'js/page-two.js' %}" type="text/javascript"></script>
  <!-- load three js -->
  <script src="{% static 'js/page-three.js' %}" type="text/javascript"></script>
  <script type="text/javascript">
    $(document).ready(function(){
      {% block js_app %}
      {% endblock %}
    });
  </script>
</body>
</html>

home/templates/home/welcome.html
{% extends 'home/base.html' %}
{% block body %}

<h1>Tests:</h1>
<ul>
  <li>1: <a href="{% url 'one:search' %}">Search</a></li>
  <li>2: <a href="{% url 'two:submit' %}">Submit form</a></li>
  <li>3: <a href="{% url 'three:translate' %}">Locale vs Internationalization</a></li>
</ul>

{% endblock %}

one/templates/one/search.html
{% extends 'home/base.html' %}

{% block js_app %}
get_list_profile_page(1);
{% endblock %}

{% block body %}


<h1>Search:</h1>
<div class="row">
  <div class="col-sm-12">
      <form id="search_profile">
        <div class="row">
          <div class="col-sm-10">
            <div class="form-group">
              <input type="search" id="id_search" class="form-control input-sm" placeholder="Type name or email">
            </div>
          </div>
          <div class="col-sm-2">
            <button type="submit" class="btn btn-info btn-block">Search</button>
          </div>
        </div>
      </form>
    <table id="profile_list" class="table table-striped table-hover table-fw-widget table-responsive">
      <thead>
        <tr>
          <th>#</th>
          <th>Name</th>
          <th>Email</th>
        </tr>
      </thead>
    <tbody></tbody>
    </table>
    <div class="pagination"></div>
    </div>
  </div>

<a href="{% url 'home:welcome' %}">Back</a>

{% endblock %}

three/templates/three/translate.html
{% extends 'home/base.html' %}

{% block js_app %}
{% endblock %}

{% block body %}


<h1 data-i18n="test-title">Local vs Internationalization:</h1>
<h2><a href="#" onclick="javascript:switch_locale('en');">EN</a> | <a href="#" onclick="javascript:switch_locale('pt-br');">PT-BR</a></h2>
<div class="row">
  <div class="col-sm-12">
      <div class="row">
        <div class="col-sm-5">
          <div class="input-group mb-3">
            <div class="input-group-prepend">
              <span class="input-group-text" data-i18n="test-currency">$</span>
            </div>
            <input type="text" class="form-control" aria-label="Amount (to the nearest dollar)">
            <div class="input-group-append">
              <span class="input-group-text">.00</span>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<a href="{% url 'home:welcome' %}" data-i18n="test-back">Back</a>

{% endblock %}

two/templates/two/submit.html
{% extends 'home/base.html' %}

{% block js_app %}
{% endblock %}

{% block body %}


<h1>Submit Form:</h1>
<div class="row">
  <div class="col-sm-12">
      <form id="submit_form">
        <div class="row">
          <div class="col-sm-5">
            <div class="form-group">
              <input type="search" id="id_name" name="name" class="form-control input-sm" placeholder="Type your name">
            </div>
          </div>
          <div class="col-sm-5">
            <div class="form-group">
              <input type="search" id="id_email" name="email" class="form-control input-sm" placeholder="Type your email">
            </div>
          </div>
          <div class="col-sm-2">
            {% csrf_token %}
            <button type="submit" class="btn btn-info btn-block">Submit</button>
          </div>
        </div>
      </form>
    </div>
  </div>

<a href="{% url 'home:welcome' %}">Back</a>

{% endblock %}